/*
 * ServicioConsumible
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.tt1.trabajo.utilidades.client;

import java.io.IOException;
import java.lang.annotation.Annotation;

import org.springframework.boot.autoconfigure.web.WebProperties.Resources.Chain;
import org.springframework.web.bind.annotation.RequestBody;

import okhttp3.Interceptor;
import okhttp3.MediaType;
import okhttp3.Request;
import okhttp3.Response;
import okio.Buffer;
import okio.BufferedSink;
import okio.GzipSink;
import okio.Okio;

/**
 * Encodes request bodies using gzip.
 *
 * Taken from https://github.com/square/okhttp/issues/350
 */
class GzipRequestInterceptor implements Interceptor {
    @Override
    public Response intercept(Chain chain) throws IOException {
        Request originalRequest = chain.request();
        if (originalRequest.body() == null || originalRequest.header("Content-Encoding") != null) {
            return chain.proceed(originalRequest);
        }

        Request compressedRequest = originalRequest.newBuilder()
                                                   .header("Content-Encoding", "gzip")
                                                   .method(originalRequest.method(), (okhttp3.RequestBody) forceContentLength(gzip(originalRequest.body())))
                                                   .build();
        return chain.proceed(compressedRequest);
    }

    private RequestBody forceContentLength(final RequestBody requestBody) throws IOException {
        final Buffer buffer = new Buffer();
        ((okhttp3.RequestBody) requestBody).writeTo(buffer);
        return new RequestBody() {
            public MediaType contentType() {
                return ((okhttp3.RequestBody) requestBody).contentType();
            }

            public long contentLength() {
                return buffer.size();
            }

            public void writeTo(BufferedSink sink) throws IOException {
                sink.write(buffer.snapshot());
            }

			@Override
			public Class<? extends Annotation> annotationType() {
				// TODO Auto-generated method stub
				return null;
			}

			@Override
			public boolean required() {
				// TODO Auto-generated method stub
				return false;
			}
        };
    }

    private RequestBody gzip(final okhttp3.RequestBody requestBody) {
        return new RequestBody() {
            public MediaType contentType() {
                return ((okhttp3.RequestBody) requestBody).contentType();
            }

            public long contentLength() {
                return -1; // We don't know the compressed length in advance!
            }

            public void writeTo(BufferedSink sink) throws IOException {
                BufferedSink gzipSink = Okio.buffer(new GzipSink(sink));
                ((okhttp3.RequestBody) requestBody).writeTo(gzipSink);
                gzipSink.close();
            }

			@Override
			public Class<? extends Annotation> annotationType() {
				// TODO Auto-generated method stub
				return null;
			}

			@Override
			public boolean required() {
				// TODO Auto-generated method stub
				return false;
			}
        };
    }
}
